theme: jekyll-theme-minimal
title: Lali Curry
description: Teaching Portfolio For Ms. Lali Curry
logo: https://github.com/lalicurry/lalicurry.github.io/blob/de4f10925f9d7be7dd9ffc3db9bcbde176c78874/assets/lcurryprofile.jpg
show_downloads: false
