theme: jekyll-theme-minimal
title: Lali Curry
description: Teaching Portfolio For Ms. Lali Curry
logo: https://github.com/lalicurry/lalicurry.github.io/blob/459c77c71a05e91fcdf21874c14765a6e83368a8/assets/lcurryprofile.jpg
show_downloads: false
